### ISSUE TITLE
Integrate SDL into the build, and use it for window creation

### ISSUE THREAD

**Issue by nmlgc** [nmlgc/ssg#40]
The industry-standard base library for portable game engines. Since Ember2528 plans to fund a complete Linux port, it makes sense to move away from Win32 sooner rather than later. This way, we avoid writing any more Win32-exclusive code for things like [SC-88Pro recordings](https://github.com/nmlgc/ssg/issues/9), only for them to be rewritten in a more portable way later.

Further issues:
* [ ] SFX and future streamed BGM: #49 
* [ ] Scaled and fullscreen window modes: #41
* [ ] Keyboard and joypad input: #22
* [ ] Graphics and rendering: #4

Non-issues:
* MIDI will continue to use pbg's original native Win32 code. SDL_mixer would be a strict downgrade, because it [can only output to the default "MIDI mapper" device](https://github.com/libsdl-org/SDL_mixer/blob/334672d85d09f16b4ecb5e2041a0ad78128c3369/src/codecs/native_midi/native_midi_win32.c#L47), which can no longer be easily changed as of Windows 7.

This obviously means that we stop maintaining all direct Win32 code. We're still going to leave the files in the repo, but just no longer compile them, allowing future pushes to still fund their continued maintenance. After all, [the ReC98-adjacent community loves tinkering with old Windows systems](https://lainnet.superglobalmegacorp.com/misc/np2gdi.html)…
